### ISSUE TITLE
Error in dependencies

### ISSUE THREAD

**Issue by woller** [beezwax/fmrest-ruby#27]
Thanks for a great gem! Found a little mistake in the dependencies.

The dependencies claim that any version of ActiveRecord is supported, however it uses features of ActiveSupport that do not exist before 5.2.3, e.g. this snippet from `lib/fmrest/spyke/model/associations.rb`

```
class_attribute :portal_options, instance_accessor: false,
                                           instance_predicate: false,
                                           default:           {}.freeze
```
Sending any options to the class_attribute method is not supported before 5.2.3.

**Comment by pilaf** [comment]
Thanks for the issue report!

I just released v0.3.2 of the gem which fixes this, and here's the relevant commit: 676f0743623ab3fa84f9102611357a2671ec2083

**Comment by pilaf** [comment]
@woller If you don't mind, please test that the new version fixes the issue for you and close it if it does.

**Comment by woller** [comment]
👍
All fixed

Thanks
