### ISSUE TITLE
Asking an empty FmRest::Spyke::Relation if it's empty, throws a FmRest::APIError::ParameterError

### ISSUE THREAD

**Issue by woller** [beezwax/fmrest-ruby#33]
The same error is thrown, when trying to get the first record in an empty relation. Would it be possible to return an empty array, when trying to do either of these operations? Then you would get the desired output (true and nil).

**Comment by pilaf** [comment]
@woller By "asking if it's empty" do you mean calling `.empty?`.

**Comment by woller** [comment]
@pilaf Yeah, that's what I meant.

**Comment by pilaf** [comment]
I just pushed a fix for this to the fix-no-matching-records-error branch (changes here: dc0a629).

Would you mind sourcing the gem from that branch and checking if it solves the issue?

**Comment by pilaf** [comment]
@woller Actually would you mind responding on #34 ?

That issue and this one appear to be the same.
